### PR TITLE
add sling domains

### PR DESCRIPTION
**Pull request by kaneawk**
Add https://www.sling.com's domains.

### CODE REVIEW

**Comment by wggwcn** [comment]
....hello sir  i found its not worked  on vultr

**Comment by kaneawk** [comment]
You should find supported IPs, like bandwagonhost los angeles, cloudsigma
san jose etc.

**Comment by ab77** [comment]
Is `cdn.hgc.com.hk` really required? Please re-test without it and confirm.

**Comment by kaneawk** [comment]
Hmmm, please just add sling domains, TVB domains is on going testing now.

**Pull request merged**
