### PR TITLE
Allow listing IPs and deleting them from this list

### PR DESCRIPTION
**Pull request by drallgood**
Hey.

I implemented a simple table of IP addresses and a button to delete them.
This is way more convenient than remembering which IP you previously registered and prevents too many IPs from cluttering up the database

### CODE REVIEW

**Comment by ab77** [comment]
Thank for that. I think the new UI update is going to confuse most people. Where there are no IPs in the list, the UI just displays `IP	Action` with no explanation what that means. I think at the very least, when there are no IPs, it should redirect to `/add`.

**Comment by drallgood** [comment]
@ab77 You're right. I was thinking about having an add button, but your solution is probably better.

**Comment by drallgood** [comment]
@ab77 Updated the PR accordingly.

**Comment by ab77** [comment]
I've tested it on a fresh Droplet and I get a HTTP error after logging in. Have you tested it?

**Comment by drallgood** [comment]
@ab77 Yes of course. but let me test it again, just to make sure I didn't miss anything

**Comment by drallgood** [comment]
@ab77  works for me, BUT I had to adapt my Caddyfile to get this running. Guess there was an update and the deprecated `proxy_header` was removed in favor of `header_upstream`

**Comment by ab77** [comment]
What exactly did you adapt? Does the `Caddyfile.template` need to be updated?

**Comment by drallgood** [comment]
@ab77 yes it needs to be updated.
Instead of `proxy_header` you have to use `header_upstream`. That's it.

**Comment by ab77** [comment]
You need to update `build.sh` and test it from a fresh install before this can be merged.

**Comment by drallgood** [comment]
@ab77 ??? I tested it with a fresh droplet and it works fine (other than the Caddyfile thing which is unrelated). So what do I need to update in the build.sh script?

**Comment by drallgood** [comment]
I'd prefer to keep the Caddyfile changes separate from this PR. This way it's easier to keep track of the changes

**Comment by drallgood** [comment]
See #241

**Comment by ab77** [comment]
OK, I've merged your Caddyfile change and tested it, all good. This PR however can't be accepted, because the admin site is still broken after test merging your updates. After logging in (Chrome), the error is:

```The 178.62.x.y page isn’t working
178.62.x.y sent an invalid response.
ERR_RESPONSE_HEADERS_MULTIPLE_LOCATION```

Please check your code and re-submit.

**Comment by drallgood** [comment]
@ab77 Weird. I installed it on a new droplet and it worked. Will double check..

**Comment by drallgood** [comment]
@ab77 found the issue. I was raising a redirect (copied the code from one of you methods) which caused this.

**Comment by ab77** [comment]
Thank you, merged.

**Pull request merged**
