### PR TITLE
Update zones.override

### PR DESCRIPTION
**Pull request by txt3rob**
Some more domains

### CODE REVIEW

**Comment by txt3rob** [comment]
The command "openssl aes-256-cbc -K $encrypted_45757fbb12c0_key -iv $encrypted_45757fbb12c0_iv -in id_rsa.travis.enc -out id_rsa.travis -d" failed and exited with 1 during .

**Comment by ab77** [comment]
That's normal (for now), until I work out how to share the encryption keys..

**Comment by txt3rob** [comment]
Ace i've written a PHP script to parse proxy auto configs so that it can create the zones for us.

**Comment by ab77** [comment]
You'll still need to do some post processing on the output to get a unique set of domains, without the host portion.

Also, proxying `akamaihd.net` domain, means that video content is delivered via the proxy as well, which is undesirable for performance reasons..

-- ab1

**Comment by txt3rob** [comment]
another option to less the load would be instead of proxy add a header of x-forwarded-for and that would work. Unotelly seem to do DNS to squid to perform this. i wonder if there is something that could do that so it's only altering the header and that way it would be less traffic.

**Pull request merged**
