### PR TITLE
Add ability to use DynDNS domains to automatically update IPs

### LINKED ISSUE #236: dynamic ip auth
hi, great project. i'm using it on aftv and when my isp change my ip then box is unusable until i re-authenticate client.
is there a way to authorize range of ip addresses (defined by mask or wildcard) or to auth dns domain updated via ddns instead of ip address? is such change contradicts with current design and is major rework or it's doable?

regards

### PR DESCRIPTION
**Pull request by drallgood**
This is a quite convenient feature which allows you to use a already set up DynDNS domain to automatically authorize an IP on the proxy server. fixes #236 

There are multiple parts to this:

1. Database of domains to check
2. A cron script that checks them every 5minutes for changes and updates the iptables rules if it detects a new IP
3. a management UI so that you can easily add or delete domains

Obviously this supports multiple domains at the same time.

I tried to integrate this in a somehow sane way into the current UI. I've also tested this with an empty droplet and it seems to be working just fine. 
Please let me know if you want me to change anything.

### CODE REVIEW

**Comment by ab77** [comment]
Awesome work! I am going to try and deploy/test this over the next few days.

**Comment by frzr** [comment]
how can unblock this website french geoblocked : http://live.mycanal.fr/tv

**Comment by jeffe13th** [comment]
This is great work @drallgood!  Really helpful.  I've installed the new version and it's working good...mostly.  I'm able to update my DynDNS if I run the ddns_updater manually via command line.  Works like a charm.  However, my Cronjob isn't working for some reason.  I added the Cronjob that you included as a template but when it runs it doesn't update.  Any ideas??  Strange that I can run the update file manually typing out the path but the Cron job that uses the same path won't work.

Once I solve this I'm good to go!  I really appreciate all the work that you and @ab77 and others have put into this.

**Comment by drallgood** [comment]
@jeffe13th 
Glad to hear you like it!

Have you checked your syslog to see whether the cronjob is even running?

**Comment by crackers8199** [comment]
has there been any movement on this?  is there any way to get the cronjob to actually update the ddns?  the cronjob is running, it's showing the logs but not actually updating anything...i'm seeing the same behavior as above, if i run it manually it works great but the cronjob isn't doing anything.

**Comment by drallgood** [comment]
@crackers8199 Nope. It seems to be working on my server and any test instance I have spun up. So, no idea why this isn't working on your machine

**Comment by crackers8199** [comment]
@drallgood it does work if I run the script manually, but that kinda defeats the purpose...if I'm going to do that I can just log in via the web interface and authorize that way.  the sys logs say the cron job is running every 5 minutes, but it just isn't updating the DB.  I even put an echo statement inside the script to see if it would output anything to a log file, and it's not doing that either unless I run it manually...

**Comment by crackers8199** [comment]
like I said, the exact same behavior as commented above.  @jeffe13th were you ever able to resolve this and get the cron working?

**Comment by jeffe13th** [comment]
I did finally get it working.  If I remember correctly I think I had forgotten to use the "sudo" command for the cronjob.  Ever since then my Dyndns has been updating automatically without any issues.  It's great.

**Comment by crackers8199** [comment]
@jeffe13th great!  can you tell me where exactly you put the sudo?  i don't understand why that would be necessary since root is the one running the crobjob, but if it is then i'll gladly put it in there if it makes everything work...just need to know where to put it.

**Comment by jeffe13th** [comment]
Below is what I have in my cronjob.  Runs every 5 minutes and updates just fine.  I have my home router configured to update my ddns account if the IP address changes.  

*/5 * * * * sudo /opt/netflix-proxy/scripts/ddns_updater.sh >> /var/log/cronoutput.log 2>&1

**Comment by bitplaio** [comment]
Hi guys. For some reason sqlite is not updated after I run the command ddns_updater.sh manually. 
Sqlite is working properly, all dyndns record I added from GUI have been saved properly, but no IP addresses are there.
Any advice?

**Pull request merged**
