### PR TITLE
additional hosts to unblock netflix

### PR DESCRIPTION
**Pull request by alardus**

### CODE REVIEW

**Comment by ab77** [comment]
Hi, any reason to add `DLCDNPortal.netflix.com`, when `*.netflix.com` is already handled by default?

**Comment by alardus** [comment]
From my experiments on `portaller.com` - with `netflix.com`/`netflix.net` you can browse USA catalog, but proxy will be detected. After `nflxvideo.net` was added - error changed to "network error, call customer service". Problem were with hosts in `ix.nflxvideo.net` subdomain, which returns "name not resolved" error for their names. 

As far as `ix.nflxvideo.net` is `DLCDNPortal.netflix.com`, I added this host separately and this make a deal - Netflix in browser works fine now. So, I thought that this may be helpful for your fight with Netflix.

**Comment by ab77** [comment]
I must be missing something..

```
$ dig DLCDNPortal.netflix.com @8.8.8.8 +short
<nothing>
$ dig ix.nflxvideo.net @8.8.8.8 +short
<nothing>
```

What's the point of proxying these hosts if the is nothing to lookup? (i.e. `NXDOMAIN`)

**Comment by alardus** [comment]
Yeah, you were right. "Streaming Error" again :-\

**Comment by ab77** [comment]
Are you sure the exit node you are using isn't blocked by Netflix? They are very active in blocking known hosting providers and anything that doesn't look like a residential ISP.

**Comment by alardus** [comment]
Yes, that was clean node in EC2 which worked perfectly through openvpn. After some manipulations described above it's also worked for other people in other networks with just different dns settings. Dns way totally broken now (for my account at least) and I'm not able to see US catalogue movies even through openvpn. "Streaming error, you are using proxy".

**Pull request closed without merging**
