### PR TITLE
Sorry more

### PR DESCRIPTION
**Pull request by txt3rob**
added some more

### CODE REVIEW

**Comment by ab77** [comment]
Is `optimizely.com` strictly necessary or did you just pick it up with all the rest of the domains?

**Comment by txt3rob** [comment]
it's not a full requirement.

want me to remove it?

**Comment by txt3rob** [comment]
i've removed it now.

**Comment by ab77** [comment]
Done, I've also changed `sniproxy.conf ` to use a simple regex, so no more changes are required to that file.

**Comment by txt3rob** [comment]
ok so it's just as simple as adding the zone's now?

**Comment by ab77** [comment]
Yep.

**Comment by txt3rob** [comment]
Amazing I might look to write a quick PHP scrip to SSH in to my VPS and add the requesting IP to the iptables. Just need to find some time to write it tho

**Comment by ab77** [comment]
I've rolled back the changes to zones.override since the 27th of August as they broke something. Feel free to have a look and see if you can work out what is breaking it..

**Comment by txt3rob** [comment]
shall have a look if i get time

**Pull request merged**
